### ISSUE TITLE
Hardcode setting for numaNodeCount under NUMA mode

### ISSUE THREAD

**Issue by troore** [clamchowder/Microbenchmarks#13]
Hi @clamchowder,

I found in MemoryBandwidth.c, under NUMA mode, there is a hardcode number (https://github.com/clamchowder/Microbenchmarks/blob/master/MemoryBandwidth/MemoryBandwidth.c#L620):

<img width="225" alt="image" src="https://github.com/clamchowder/Microbenchmarks/assets/1692681/8b79f794-2f37-482d-a9ea-9d08df429bd2">

As the comment indicates, it may be for KNL. So should we recover the `numaNodeCount` back to `numa_max_node() + 1` for other CPUs?

Thanks,
troore

**Comment by clamchowder** [comment]
I modified the test to investigate specific NUMA platforms. NUMA in general is not supported by the tests here. If you wish to investigate a NUMA setup, you're on your own and might be better off writing your own microbenchmarks from scratch
