### ISSUE TITLE
ReturnStackTest may need extra alignment on Golden Cove

### ISSUE THREAD

**Issue by jiegec** [clamchowder/Microbenchmarks#14]
In [Popping the Hood on Golden Cove](https://chipsandcheese.com/2021/12/02/popping-the-hood-on-golden-cove/), the return prediction behavior of Golden Cove seems weird: no clear jump up observed. This is possibly due to too many call/ret pairs in the same cache line. If an extra alignment directive is added so that the functions reside in different cache lines:

```diff
diff --git a/AsmGen/tests/ReturnStackTest.cs b/AsmGen/tests/ReturnStackTest.cs
index d940393..9d768cd 100644
--- a/AsmGen/tests/ReturnStackTest.cs
+++ b/AsmGen/tests/ReturnStackTest.cs
@@ -34,6 +34,7 @@ namespace AsmGen
                 {
                     string funcName = GetFunctionName(callDepth, callIdx);
                     sb.AppendLine($".global {funcName}");
+                    sb.AppendLine($".align 64");
                     sb.AppendLine($"{funcName}:");
                     if (callIdx < callDepth - 1)
                     {
```

We can observe a clear jump up at ~20 calls:

```
Return Stack Depth Test:
1,0.508000
2,0.168000
3,0.172000
4,0.166000
5,0.166000
6,0.198000
7,0.228000
8,0.186000
9,0.184000
10,0.182000
11,0.182000
12,0.180000
13,0.178000
14,0.190000
15,0.188000
16,0.188000
17,0.186000
18,0.184000
19,0.184000
20,0.182000
21,0.406000
22,0.440000
23,0.528000
```

This looks promising, since Sunny Cove has 17-entry RAS.

**Comment by edisonchan** [comment]
Currently, the test results of this open source code seem to be very different from the results in the CNC paper.
![image](https://github.com/user-attachments/assets/b04b2451-3d0b-4c6d-a06e-f3a80c79c66d)

**Comment by jiegec** [comment]
> Currently, the test results from master branch seems to be very different from the results in the CNC's articles . ![image](https://private-user-images.githubusercontent.com/8596506/356108133-b04b2451-3d0b-4c6d-a06e-f3a80c79c66d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNjE0MzQsIm5iZiI6MTcyMzE2MTEzNCwicGF0aCI6Ii84NTk2NTA2LzM1NjEwODEzMy1iMDRiMjQ1MS0zZDBiLTRjNmQtYTA2ZS1mM2E4MGM3OWM2NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMjM1MjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE5NjlkZjQzMTFkNzAwOTNmZTM2MzU1NzUyYWRkNTI0MDEyZGFhYmRiZTM2NDIzZGNlZDY2NTc4ZTA1NzkzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hSKHyCj-j2JGVF8EsOQs-1v6I1q8KGzTS5PcEE_8haI)

Yes, the results after adding the extra alignment are like:

![image](https://github.com/user-attachments/assets/6b09014f-f998-46ac-9719-fe0bc01c038b)

**Comment by clamchowder** [comment]
Thanks, alignment indeed matters here, and I see 20 return stack entries on Redwood Cove. I'll get this into the master branch. Currently I'm a bit busy with other changes

**Comment by clamchowder** [comment]
Increased padding between generated test functions and calls/returns
