### ISSUE TITLE
no alternatives to building with vs2019?

### ISSUE THREAD

**Issue by abondarev84** [clamchowder/Microbenchmarks#3]
any plans on creating a linux based cli build instructions and tests?
I ran a couple of the specific makes that had a makefile in them and arm options.

to build the "main" clammicrobench I've tried using msbuild on ubuntu 20.04 running on EC2 instance (aarch64 cpu).
in the solution file I'm only seeing x64 and win32 options for build.
```          {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Debug|x64.ActiveCfg = Debug|x64
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Debug|x64.Build.0 = Debug|x64
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Debug|x86.ActiveCfg = Debug|Win32
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Debug|x86.Build.0 = Debug|Win32
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Release|x64.ActiveCfg = Release|x64
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Release|x64.Build.0 = Release|x64
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Release|x86.ActiveCfg = Release|Win32
                {7E8CF2BA-57A7-4B42-B721-97E02BF9A8B8}.Release|x86.Build.0 = Release|Win32
```
it's very possible that I'm missing something here but I would rather ask than assume and make a mess.
NASM is available only in rpm format (possible to install on ubuntu but somewhat too forced and might cause other issues down the line).

reached this repo basically after reading the blog post about graviton 3 (https://chipsandcheese.com/2022/05/29/graviton-3-first-impressions/)
thanks in advance

**Comment by clamchowder** [comment]
You can build and run the AsmGen project on Windows, then upload the generated source files (clammicrobench.c, clammicrobench_x86.s or clammicrobench_arm.s) to the linux VM, and build it there.

**Comment by clamchowder** [comment]
Building the structure size benchmarks with VS is no longer supported, and replaced with mingw-w64 cross compile.
